services:
  redis:
    image: redis:7-alpine
    container_name: sdlc-redis
    ports:
      - "6379:6379"
    networks:
      - sdlc-network

  client-api:
    build: 
      context: .
      dockerfile: client/Dockerfile
    container_name: sdlc-client-api
    ports:
      - "3000:3000"
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - NODE_ENV=development
    depends_on:
      - redis
    networks:
      - sdlc-network

  frontend:
    build: ./chatbot-fe
    container_name: sdlc-frontend
    ports:
      - "4173:4173"
    depends_on:
      - client-api
    networks:
      - sdlc-network

networks:
  sdlc-network:
    driver: bridge